### ISSUE TITLE
Confuse ray

### ISSUE THREAD

**Issue by Stavinair** [SMOLKEYS/communityturretsuggestions#1]
Add an "x" to all checkboxes([X]) to ensure that your suggestion gets created.

- I have checked the mod to make sure that this turret suggestion is not in the mod. [X]

- I have checked in the open and closed issues to ensure that this suggestion has not been made yet. [X]

Makes enemy units go the opposite direction for a brief while

**Comment by SMOLKEYS** [comment]
cannot do.
Im quite new to turret modding so im only limited to more simpler stuff.
